# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio-ios-gabriel-rodrigues' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for desafio-ios-gabriel-rodrigues

  target 'desafio-ios-gabriel-rodriguesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafio-ios-gabriel-rodriguesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
